- name: Optimization for Apache
  hosts: localhost
  connection: local
  vars:    
    SETUP_PATH: "/tmp/BashServerSetup/"
  tasks:  
      - name: Install libapache2-mod-geoip
        apt:
          name: libapache2-mod-geoip
          state: present

      - name: Configure Apache MPM and modules
        shell: |
            a2enmod proxy_fcgi setenvif && a2enconf php7.0-fpm ; a2enconf php7.1-fpm ; a2enconf php7.2-fpm ; a2enconf php7.3-fpm ; a2enconf php7.4-fpm
            a2dismod php7.0  ; a2dismod php7.1 ; a2dismod php7.2 ; a2dismod php7.3 ; a2dismod php7.4
            kill -9 `ps -ef | grep php-fpm | grep -v grep | awk '{print $2}'`
            a2enmod http2
            service apache2 restart
            a2dismod mpm_prefork && a2enmod mpm_event
            service apache2 restart
            service php7.2-fpm restart ; service php7.3-fpm restart ; service php7.4-fpm restart
            apt remove php5.4-fpm      
            service webmin start
        become: yes

      - name: Enable Apache modules
        command: a2enmod {{ item }}
        with_items:
          - expires
          - headers
      
      - name: Enable HTTP/2 globally
        lineinfile:
          path: /etc/apache2/apache2.conf
          line: "Protocols h2 http/1.1"