- name: Initiate Core Setup
  hosts: localhost
  connection: local
  vars:    
    SETUP_PATH: "/var/BashServerSetup/"
  tasks: 

    - name: Print hostname
      debug:
        msg: "Hostname of the target host is {{ ansible_fqdn }}"   

    - name: Upgrade the package
      apt:
        name: 
        - imagemagick
        - libmagickwand-dev
        - imagemagick
        - php-dev
        - libdigest-perl-md5-perl
        - htop
        - ncdu
        - zip
        - screen
        - nfs-common
        - nethogs
        - net-tools
        state: present


    - name: Install btop via snap
      shell :  snap install btop
   

    - name: Clean up the temporary directory
      ansible.builtin.file:
        path: /tmp/btop
        state: absent
        force: true  

    - name: Set timezone to Asia/Makassar
      command: timedatectl set-timezone Asia/Makassar   

    - name: Download Fail2ban deb package
      get_url:
        url: https://github.com/fail2ban/fail2ban/releases/download/1.1.0/fail2ban_1.1.0-1.upstream1_all.deb
        dest: /tmp/fail2ban_1.1.0-1.upstream1_all.deb

    - name: Install Fail2ban
      apt:
        deb: /tmp/fail2ban_1.1.0-1.upstream1_all.deb

    - name: Disable specific features in Virtualmin
      block:
        - name: Disable DNS feature
          command: virtualmin disable-feature --dns --all-domains

        - name: Disable Mail feature
          command: virtualmin disable-feature --mail --all-domains    

    - name: Stop services
      service:
        name: "{{ item }}"
        state: stopped
      with_items:
        - mysql
        - fail2ban
        - ssh

    - name: Install Screen
      apt:
        name: 
        - screen
        - monitorix
        state: present    

    - name: Install PHP dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - php7.3
        - php7.3-fpm
        - php7.3-imagick
        - php7.3-common
        - php7.3-mysql
        - php7.3-xml
        - php7.3-curl
        - php7.3-mbstring
        - php7.3-mcrypt
        - php7.3-gmp
        - php7.4
        - php7.4-fpm
        - php7.4-common
        - php7.4-mysql
        - php7.4-xml
        - php7.4-mbstring
        - php7.4-imagick
        - php7.4-curl
        - php7.4-mcrypt
        - php7.4-gmp
        - php7.4-gd
        - php7.4-intl
        - php8.1
        - php8.1-fpm
        - php8.1-common
        - php8.1-mysql
        - php8.1-xml
        - php8.1-mbstring
        - php8.1-imagick
        - php8.1-curl
        - php8.1-mcrypt
        - php8.1-gmp
        - php8.1-gd
        - php8.1-intl
        - php8.2
        - php8.2-fpm
        - php8.2-common
        - php8.2-mysql
        - php8.2-xml
        - php8.2-mbstring
        - php8.2-imagick
        - php8.2-curl
        - php8.2-mcrypt
        - php8.2-gmp
        - php8.2-gd
        - php8.2-intl
        - php8.3
        - php8.3-fpm
        - php8.3-common
        - php8.3-mysql
        - php8.3-xml
        - php8.3-mbstring
        - php8.3-imagick
        - php8.3-curl
        - php8.3-mcrypt
        - php8.3-gmp
        - php8.3-gd
        - php8.3-intl
      ignore_errors: true
        

  