- name: Initiate Core Setup
  hosts: localhost
  connection: local
  vars:    
    SETUP_PATH: "/tmp/BashServerSetup/"
  tasks: 

    - name: Print hostname
      debug:
        msg: "Hostname of the target host is {{ ansible_fqdn }}"   

    - name: Upgrade the package
      apt:
        name: 
        - imagemagick
        - libmagickwand-dev
        - imagemagick
        - php-dev
        - libdigest-perl-md5-perl
        - htop
        - ncdu
        - zip
        - screen
        - nfs-common
        - nethogs
        - net-tools
        state: present
      
    - name: Install PyMySQL using pip
      pip:
        name: pymysql
        state: present


    - apt_repository:
        repo: ppa:bashtop-monitor/bashtop
        update_cache: yes

    - name: Add bashtop repository and install bashtop
      apt:
        name: bashtop
        state: present

    - name: Set timezone to Asia/Makassar
      command: timedatectl set-timezone Asia/Makassar   

    - name: Download Fail2ban deb package
      get_url:
        url: https://github.com/fail2ban/fail2ban/releases/download/0.11.2/fail2ban_0.11.2-1.upstream1_all.deb 
        dest: /tmp/fail2ban_0.11.2-1.upstream1_all.deb

    - name: Install Fail2ban
      apt:
        deb: /tmp/fail2ban_0.11.2-1.upstream1_all.deb  

    - name: Disable specific features in Virtualmin
      block:
        - name: Disable DNS feature
          command: virtualmin disable-feature --dns --all-domains

        - name: Disable Mail feature
          command: virtualmin disable-feature --mail --all-domains    

    - name: Stop services
      service:
        name: "{{ item }}"
        state: stopped
      with_items:
        - mysql
        - fail2ban
        - sshd

    - name: Install Screen
      apt:
        name: 
        - screen
        - monitorix
        state: present    

    - name: Install PHP and its dependencies
      apt:
        name: 
        - software-properties-common
        - php7.3
        - php7.3-fpm
        - php7.3-imagick
        - php7.3-common
        - php7.3-mysql
        - php7.3-xml
        - php7.3-curl
        - php7.3-mbstring
        - php7.3-mcrypt
        - php7.3-gmp
        - php7.4
        - php7.4-fpm
        - php7.4-common
        - php7.4-mysql
        - php7.4-xml
        - php7.4-mbstring
        - php7.4-imagick
        - php7.4-curl
        - php7.4-mcrypt
        - php7.4-gmp
        - php8.1
        - php8.1-fpm
        - php8.1-common
        - php8.1-mysql
        - php8.1-xml
        - php8.1-mbstring
        - php8.1-imagick
        - php8.1-curl
        - php8.1-mcrypt
        - php8.1-gmp

    - name: Modify PHP configuration for all domains
      command: virtualmin modify-php-ini --all-domains --ini-name {{ item.ini_name }} --ini-value {{ item.ini_value }}
      with_items:
        - { ini_name: "memory_limit", ini_value: "128M" }
        - { ini_name: "upload_max_filesize", ini_value: "500M" }
        - { ini_name: "post_max_size", ini_value: "500M" }


    - name: Change Webmin port
      replace:
        path: /etc/webmin/miniserv.conf
        regexp: "port=10000"
        replace: "port=9191"

    - name: Update SSHD configuration
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "{{ item }}"
      with_items:
        - "#edited by serverAutomation by navotera :: share-system.com"
        - "ClientAliveInterval 1200"
        - "ClientAliveCountMax 3"
      

    - name: Disable root SSH login with password
      replace:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin.*"
        replace: "PermitRootLogin prohibit-password"
    

    - name: Get PASSWORD value
      shell: grep '^PASSWORD=' ~/server.config | cut -d'=' -f2
      register: PASSWD
      no_log: true

    - name: Change root password
      user:
        name: root
        password: "{{ PASSWD.stdout | password_hash('sha512') }}"

    - name: Update Virtualmin configuration for new domain creation
      lineinfile:
        path: /etc/webmin/virtual-server/config
        line: "{{ item }}"
      with_items:
        - "home_format=$DOM"
        - "wizard_run=1"

    - name: Download rclone installation script
      get_url:
        url: https://rclone.org/install.sh
        dest: /tmp/install_rclone.sh

    - name: Run rclone installation script
      command: sudo bash /tmp/install_rclone.sh

    - name: Enable start on boot for fail2ban
      service:
        name: fail2ban
        state: started
        enabled: true

    - name: Add ports to firewall
      firewalld:
        zone: public
        permanent: yes
        state: enabled
        port: "{{ item }}/tcp"
      with_items:
        - 9191 #webmin
        - 9292 #pamin
        - 9393 #monitorix
    
    - name: Reload firewalld
      shell: firewall-cmd --reload