- name: Finalize
  hosts: localhost
  connection: local
  become: yes
  vars:
    JAIL_CONFIG_URL: "/tmp/BashServerSetup/serverInit/jail.local"
    CORE_FILE_URL: "/tmp/BashServerSetup/core.sh"
    SETUP_PATH: "/tmp/BashServerSetup/"
    IP_ADDRESS: "{{ ansible_default_ipv4.address }}"
  tasks:
    #- name: Change needrestart configuration
    #  lineinfile:
    #    path: /etc/needrestart/needrestart.conf
    #    regexp: '#\$nrconf{restart} = '\''i'\'';'
    #    line: '$nrconf{restart} = '\''a'\'';'

  
    - name: Start MySQL service
      service:
        name: mysql
        state: started


    - name: Get PASSWORD value
      shell: grep '^PASSWORD=' ~/server.config | cut -d'=' -f2
      register: PASSWD
      no_log: true

    - name: Show what is the password for debugging
      debug:
        msg: "The retrieved PASSWORD value is {{ PASSWD.stdout }}"

    #biar bagaimana pakai ansible rules saat bikin new user tidak bisa selalu 'unable to connect'
    - name: Create the root database user with all privileges
      shell: sh /tmp/BashServerSetup/playbook/sh/create_root_db_user.sh

    - name: Start webmin
      command: /usr/share/webmin/changepass.pl /etc/webmin root "{{ PASSWD.stdout }}"

    - name: Set up cron jobs
      cron:
        name: "Run /etc/webmin/status/monitor.pl every 5 minutes"
        minute: "*/5"
        job: "/etc/webmin/status/monitor.pl"
        state: present

    - name: Add cron job to stop services
      cron:
        name: "Stop services every 4 hours"
        minute: "0"
        hour: "*/4"
        job: "sudo service pamin stop"
        state: present


    - name: Disable current swap
      command: swapoff /swapfile
      ignore_errors: yes

    - name: Get memory information
      setup:
        filter: ansible_memtotal_mb

    - name: Set swap file size based on memory
      set_fact:
        swap_size_gb: "{{ 2 if ansible_memtotal_mb < 4096 else 6 }}"

    - name: Create a new swap file
      command: fallocate -l {{ swap_size_gb }}G /swapfile

    - name: Display swap file information
      command: ls -lh /swapfile

    - name: Format swap file
      command: mkswap /swapfile

    - name: Enable the new swap file
      command: swapon /swapfile

    - name: Add the swap file to /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: '/swapfile none swap sw 0 0'
        state: present

