- name: Preparing setup
  hosts: localhost
  connection: local
  become: yes
  vars:
    JAIL_CONFIG_URL: "/tmp/BashServerSetup/serverInit/jail.local"
    CORE_FILE_URL: "/tmp/BashServerSetup/core.sh"
    SETUP_PATH: "/tmp/BashServerSetup/"
    IP_ADDRESS: "{{ ansible_default_ipv4.address }}"
  tasks:
    #- name: Change needrestart configuration
    #  lineinfile:
    #    path: /etc/needrestart/needrestart.conf
    #    regexp: '#\$nrconf{restart} = '\''i'\'';'
    #    line: '$nrconf{restart} = '\''a'\'';'

  
    # - name: Start MySQL service
    #   service:
    #     name: mysql
    #     state: started


    - name: Get PASSWORD value
      shell: grep '^PASSWORD=' ~/server.config | cut -d'=' -f2
      register: PASSWD
      no_log: true

    - name: Use PASSWORD value in another task
      debug:
        msg: "The retrieved PASSWORD value is {{ PASSWD.stdout }}"


  


    # - name: Create MySQL User
    #   mysql_user:
    #     name: "root_db"
    #     password: "{{ PASSWD.stdout }}"
    #     host: "localhost"

    - name: Create the root database user with all privileges
      mysql_user:
        name: "root_db"
        password: "{{ PASSWD.stdout }}"
        host: localhost
        priv: "*.*:ALL"
        state: present
        login_user: "root"

    - name: Start webmin
      command: /usr/share/webmin/changepass.pl /etc/webmin root "{{ PASSWD.stdout }}"

    - name: Reboot the server
      command: reboot
      async: 0
      poll: 0
