- name: Preparing setup
  hosts: localhost
  connection: local
  become: yes
  vars:
    JAIL_CONFIG_URL: "/tmp/BashServerSetup/serverInit/jail.local"
    CORE_FILE_URL: "/tmp/BashServerSetup/core.sh"
    SETUP_PATH: "/tmp/BashServerSetup/"
    IP_ADDRESS: "{{ ansible_default_ipv4.address }}"
  tasks:
    #- name: Change needrestart configuration
    #  lineinfile:
    #    path: /etc/needrestart/needrestart.conf
    #    regexp: '#\$nrconf{restart} = '\''i'\'';'
    #    line: '$nrconf{restart} = '\''a'\'';'

    - name: Set custom hostname
      hostname:
        name: "{{ ansible_default_ipv4.address.split('.')[3] }}.opensynergic.com"

    - name: Make the shell script executable
      script: "{{ SETUP_PATH }}playbook/sh/create_server_config.sh"
      args:
        executable: /bin/bash

    - name: Start MySQL service
      service:
        name: mysql
        state: started

    - name: Create MySQL user root_db
      mysql_user:
        name: root_db
        host: localhost
        password: "{{ PASSWD }}"
        priv: '*.*:ALL'

    - name: Start webmin
      command: /usr/share/webmin/changepass.pl /etc/webmin root "{{ PASSWD }}"

    - name: Reboot the server
      command: reboot
      async: 0
      poll: 0
