- name: BashServer Setup Initiate
  hosts: localhost
  connection: local 
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install zip package
      apt:
        name: zip
        state: present

    - name: Upgrade all packages
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes
        autoremove: yes
        autoclean: yes    

    - name: Run core
      include_tasks: /tmp/BashServerSetup/playbook/preparing.yml
  
