#only test file for debug a task

- name: BashServer Setup Initiate
  hosts: localhost
  connection: local
  become: yes
  tasks: 
  - name: Optimize limits for www-data and mysql
    blockinfile:
      path: /etc/security/limits.conf
      block: |
        #optimized by navotera - share-system.com
        www-data   soft  nofile   1048576
        www-data   soft  nproc   1048576
        nginx      soft  nofile   1048576
        nginx      soft  nproc   1048576
        mysql      soft  memlock   unlimited
        mysql      hard  memlock   unlimited
        mysql      hard  nofile   30720
        mysql      soft  nofile   20480
        mysql      soft  nproc    16384
        mysql      soft  fsize    unlimited

  - name: Configure system settings
    blockinfile:
      path: "{{ item.path }}"
      block: "{{ item.block }}"
    with_items:
      - {
          path: "/etc/pam.d/common-session",
          block: "session required pam_limits.so",
        }
      - {
          path: "/etc/sysctl.conf",
          block: "fs.file-max = 2097152\nfs.nr_open = 1048576",
        }

  - name: Configure Apache MPM and modules
    shell: |
      a2enmod proxy_fcgi setenvif && a2enconf php7.0-fpm ; a2enconf php7.1-fpm ; a2enconf php7.2-fpm ; a2enconf php7.3-fpm ; a2enconf php7.4-fpm
      a2dismod php7.0  ; a2dismod php7.1 ; a2dismod php7.2 ; a2dismod php7.3 ; a2dismod php7.4
      kill -9 `ps -ef | grep php-fpm | grep -v grep | awk '{print $2}'`
      a2enmod http2
      service apache2 restart
      a2dismod mpm_prefork && a2enmod mpm_event
      service apache2 restart
      service php7.2-fpm restart ; service php7.3-fpm restart ; service php7.4-fpm restart
      apt remove php5.4-fpm      
      service webmin start
    become: yes

  - name: Enable start on boot for fail2ban
    service:
      name: fail2ban
      state: started
      enabled: true

  - name: Remove server banner from sshd
    lineinfile:
      path: /etc/pam.d/sshd
      state: present
      backrefs: yes
      regexp: '^[^#]*\<pam_motd.so\>'
      line: "#&"

  - name: Add ports to firewall
    firewalld:
      zone: public
      permanent: yes
      state: enabled
      port: "{{ item }}/tcp"
    with_items:
      - 9191 #webmin
      - 9292 #pamin
      - 9393 #monitorix
  
  - name: Reload firewalld
    shell: firewall-cmd --reload      
