- name: BashServer Setup Initiate
  hosts: localhost
  connection: local
  become: yes
  tasks: 

  - name: Download Fail2ban deb package
    get_url:
      url: https://github.com/fail2ban/fail2ban/releases/download/0.11.2/fail2ban_0.11.2-1.upstream1_all.deb 
      dest: /tmp/fail2ban_0.11.2-1.upstream1_all.deb

  - name: Install Fail2ban
    apt:
      deb: /tmp/fail2ban_0.11.2-1.upstream1_all.deb


  # - name: Add ports to firewall
  #   firewalld:
  #     zone: public
  #     permanent: yes
  #     state: enabled
  #     port: "{{ item }}/tcp"
  #   with_items:
  #     - 9191 #webmin
  #     - 9292 #pamin
  #     - 9393 #monitorix
  
  # - name: Reload firewalld
  #   ansible.builtin.service:
  #     name: firewalld
  #     state: reloaded