- name: BashServer Setup Initiate
  hosts: localhost
  connection: local
  become: yes
  tasks: 

  - name: Get PASSWORD value
    shell: grep '^PASSWORD=' ~/server.config | cut -d'=' -f2
    register: PASSWD
    no_log: true

  - name: Change root password
    user:
      name: root
      password: "{{ PASSWD.stdout | password_hash('sha512') }}"


  # - name: Add ports to firewall
  #   firewalld:
  #     zone: public
  #     permanent: yes
  #     state: enabled
  #     port: "{{ item }}/tcp"
  #   with_items:
  #     - 9191 #webmin
  #     - 9292 #pamin
  #     - 9393 #monitorix
  
  # - name: Reload firewalld
  #   ansible.builtin.service:
  #     name: firewalld
  #     state: reloaded