- name: install Modsecurity 2 latest version
  hosts: localhost
  connection: local 
  tasks:

  - name : URL of latest version 
    set_fact : 
      latest_version : https://github.com/SpiderLabs/ModSecurity/releases/download/v2.9.6/modsecurity-2.9.6.tar.gz
      tar_folder : modsecurity-2.9.6     

  - name: Install Apache
    ansible.builtin.apt:
      name: apache2
      state: present
      
  - name: Install a list of packages
    ansible.builtin.apt:
      pkg:
      - apache2-dev
      - python
      - apt-utils
      - autoconf
      - automake
      - build-essential
      - libpcre3-dev
      - libcurl4-openssl-dev
      - libgeoip-dev
      - liblmdb-dev
      - libpcre++-dev
      - libtool 
      - libyajl-dev
      - libxml2-dev
      - pkgconf
      - zlib1g-dev
      - doxygen
      - valgrind  
      state: present
      update_cache: yes
    register: install_needed
    retries: 5
    until: install_needed is success

  - name: "Clone the mod "
    shell: |
      cd /tmp/
      git clone https://github.com/SpiderLabs/ModSecurity.git
      cd /tmp/ModSecurity/ && ./build.sh      
      cd /tmp/ModSecurity/ && git submodule init 
      cd /tmp/ModSecurity/ && git submodule update      

  - name: Make install 
    shell : cd /tmp/ModSecurity && ./configure && make && make install 
    register: make_install
    retries: 10
    until: make_install is success
    debugger: on_failed
    async: 1800
    poll: 10




  # - name: Wget the file 
  #   shell: |
  #     wget {{ latest_version }} && tar -xvf {{tar_folder}}.tar.gz && mv {{ tar_folder}} modsecurity
  
  # - name: Run build 
  #   shell: cd /tmp/modsecurity/ && ./autogen.sh

  # - name: Make install 
  #   shell : |
  #     cd /tmp/modsecurity && ./configure && make && make install 
  #   register: make_install
  #   retries: 10
  #   until: make_install is success
  #   debugger: on_failed
  #   async: 1800
  #   poll: 10

  - name: Download crs and unicode
    shell : |
      mkdir -p /etc/apache2/modsecurity.d
      mkdir -p /etc/apache2/modsecurity.d/exception
      git clone https://github.com/SpiderLabs/owasp-modsecurity-crs.git /etc/apache2/modsecurity.d/owasp-crs
      cp /etc/apache2/modsecurity.d/owasp-crs/crs-setup.conf.example  /etc/apache2/modsecurity.d/owasp-crs/crs-setup.conf
      wget https://raw.githubusercontent.com/SpiderLabs/ModSecurity/v2/master/unicode.mapping -P /etc/apache2/conf-available/
      wget https://github.com/navotera/BashServerSetup/raw/master/app/modsecurity/files/v2/init.conf -P /etc/apache2/modsecurity.d/    
      wget https://github.com/navotera/BashServerSetup/raw/master/app/modsecurity/files/exception/_ojs.conf -P /etc/apache2/modsecurity.d/exception

  - name: copy the mod_security2.so to apache2 folder 
    shell : cp /tmp/Modsecurity/modsecurity.conf-recommended /etc/apache2/modsecurity.d/modsecurity2.conf

  - name: Activate mod security
    lineinfile:
        path: /etc/apache2/apache2.conf
        insertafter: EOF
        line: "{{ item.line }}"
    with_items:
        - { line: LoadModule security2_module /usr/lib/apache2/modules/mod_security2.so }
        - { line: Include /etc/apache2/modsecurity.d/init.conf }

  #https://raspi.emawind.com/devnote/linux-modsecurity-install-howto.html
  - name: Add module unique on apache2
    shell: |
      cd /etc/apache2/mods-enabled
      ln -s ../mods-available/unique_id.load .
      service apache2 reload       




